let cards = [
    {
        image : "../img/profil1.jpg",
        name : "Pablo",
        fullName : "Pablo Carrillo",
        rank : "../img/bronze-medal.png",
        subject : "Matemáticas financieras",
        career : 'Administraión',
        semester : 5,
        rating : "4/5",
        price : '$250',
        promedio : 9.8,
        comments : ['Me gustó, cómo me explicó lo que no entendía, es muy paciente', 'Tomen asesoría con él, entendí todo', 'Pensé que entendería este tema, muchas gracias', 'Excelente', 'Sabe mucho y explica muy bien.', 'Me ayudaste mucho ¡Gracias!', 'Entendí todo', 'Muy buena asesoría.', '¡Gracias! Me siento preparado para el examen.'],
        university : 'Anáhuac Mayab',
        description : 'Soy un estudiante que le encanta las matemáticas y enseñar a los demás. Además, soy paciente y si el tema se te complica mucho, haré todo lo posible hasta que lo entiendas.',
    },
    {
        image : "../img/profil5.jpg",
        name : "Tarik",
        fullName : "Tarik Rodriguez",
        rank : "../img/bronze-medal.png",
        subject : "Matemáticas financieras",
        career : 'Finanzas y contabilidad',
        semester : 4,
        rating : "4/5",
        price : '$250',
        promedio : 9.7,
        comments : ['Me gustó, cómo me explicó lo que no entendía, es muy paciente', 'Tomen asesoría con él, entendí todo', 'Pensé que entendería este tema, muchas gracias', 'Excelente', 'Sabe mucho y explica muy bien.', 'Me ayudaste mucho ¡Gracias!', 'Entendí todo', 'Muy buena asesoría.', '¡Gracias! Me siento preparado para el examen.'],
        university : 'Anáhuac Mayab',
        description : 'Soy un estudiante que le encanta las matemáticas y enseñar a los demás. Además, soy paciente y si el tema se te complica mucho, haré todo lo posible hasta que lo entiendas.',
    },
    {
        image : "../img/profil2.jpg",
        name : "Maria",
        fullName : "Maria Méndez",
        rank : "../img/gold-medal.png",
        subject : "Matemáticas financieras",
        career : 'Negocios inernacionales',
        semester : 4,
        rating : "5/5",
        price : '$300',
        promedio : 9.5,
        comments : ['Me gustó, cómo me explicó lo que no entendía, es muy paciente', 'Tomen asesoría con él, entendí todo', 'Pensé que entendería este tema, muchas gracias', 'Excelente', 'Sabe mucho y explica muy bien.', 'Me ayudaste mucho ¡Gracias!', 'Entendí todo', 'Muy buena asesoría.', '¡Gracias! Me siento preparado para el examen.'],
        university : 'Anáhuac Mayab',
        description : 'Soy una estudiante que le encanta las matemáticas y enseñar a los demás. Además, soy paciente y si el tema se te complica mucho, haré todo lo posible hasta que lo entiendas.',
    },
    {
        image : "../img/profil7.jpg",
        name : "Elena",
        fullName : "Elena Sanz",
        rank : "../img/gold-medal.png",
        subject : "Matemáticas financieras",
        career : 'Administraión',
        semester : 5,
        rating : "4.5/5",
        price : '$300',
        promedio : 9.8,
        comments : ['Me gustó, cómo me explicó lo que no entendía, es muy paciente', 'Tomen asesoría con él, entendí todo', 'Pensé que entendería este tema, muchas gracias', 'Excelente', 'Sabe mucho y explica muy bien.', 'Me ayudaste mucho ¡Gracias!', 'Entendí todo', 'Muy buena asesoría.', '¡Gracias! Me siento preparado para el examen.'],
        university : 'Anáhuac Mayab',
        description : 'Soy una estudiante que le encanta las matemáticas y enseñar a los demás. Además, soy paciente y si el tema se te complica mucho, haré todo lo posible hasta que lo entiendas.',
    },
    {
        image : "../img/profil8.jpg",
        name : "Job",
        fullName : "Job López",
        rank : "../img/noRank.png",
        subject : "Matemáticas financieras",
        career : 'Negocios inernacionales',
        semester : 2,
        rating : "4/5",
        price : '$250',
        promedio : 9.4,
        comments : ['Me gustó, cómo me explicó lo que no entendía, es muy paciente', 'Tomen asesoría con él, entendí todo', 'Pensé que entendería este tema, muchas gracias', 'Excelente', 'Sabe mucho y explica muy bien.', 'Me ayudaste mucho ¡Gracias!', 'Entendí todo', 'Muy buena asesoría.', '¡Gracias! Me siento preparado para el examen.'],
        university : 'Anáhuac Mayab',
        description : 'Soy un estudiante que le encanta las matemáticas y enseñar a los demás. Además, soy paciente y si el tema se te complica mucho, haré todo lo posible hasta que lo entiendas.',
    },
    {
        image : "../img/profil6.png",
        name : "Paola",
        fullName : "Paola Sánchez",
        rank : "../img/noRank.png",
        subject : "Matemáticas financieras",
        career : 'Finanzas y contabilidad',
        semester : 2,
        rating : "4/5",
        price : '$200',
        promedio : 9.9,
        comments : ['Me gustó, cómo me explicó lo que no entendía, es muy paciente', 'Tomen asesoría con él, entendí todo', 'Pensé que entendería este tema, muchas gracias', 'Excelente', 'Sabe mucho y explica muy bien.', 'Me ayudaste mucho ¡Gracias!', 'Entendí todo', 'Muy buena asesoría.', '¡Gracias! Me siento preparado para el examen.'],
        university : 'Anáhuac Mayab',
        description : 'Soy una estudiante que le encanta las matemáticas y enseñar a los demás. Además, soy paciente y si el tema se te complica mucho, haré todo lo posible hasta que lo entiendas.',
    },
    {
        image : "../img/profil3.jpg",
        name : "Samuel",
        fullName : "Samuel Fernández",
        rank : "../img/gold-medal.png",
        subject : "Matemáticas financieras",
        career : 'Finanzas y contabilidad',
        semester : "6",
        rating : "4.5/5",
        price : '$280',
        promedio : 9.6,
        comments : ['Me gustó, cómo me explicó lo que no entendía, es muy paciente', 'Tomen asesoría con él, entendí todo', 'Pensé que entendería este tema, muchas gracias', 'Excelente', 'Sabe mucho y explica muy bien.', 'Me ayudaste mucho ¡Gracias!', 'Entendí todo', 'Muy buena asesoría.', '¡Gracias! Me siento preparado para el examen.'],
        university : 'Anáhuac Mayab',
        description : 'Soy un estudiante que le encanta las matemáticas y enseñar a los demás. Además, soy paciente y si el tema se te complica mucho, haré todo lo posible hasta que lo entiendas.',
    },
    {
        image : "../img/profil4.jpg",
        name : "Juan",
        fullName : "Juan López",
        rank : "../img/noRank.png",
        subject : "Matemáticas financieras",
        career : 'Negocios inernacionales',
        semester : 5,
        rating : "4.5/5",
        price : '$250',
        promedio : 9.2,
        comments : ['Me gustó, cómo me explicó lo que no entendía, es muy paciente', 'Tomen asesoría con él, entendí todo', 'Pensé que entendería este tema, muchas gracias', 'Excelente', 'Sabe mucho y explica muy bien.', 'Me ayudaste mucho ¡Gracias!', 'Entendí todo', 'Muy buena asesoría.', '¡Gracias! Me siento preparado para el examen.'],
        university : 'Anáhuac Mayab',
        description : 'Soy un estudiante que le encanta las matemáticas y enseñar a los demás. Además, soy paciente y si el tema se te complica mucho, haré todo lo posible hasta que lo entiendas.',
    },
    {
        image : "../img/profil9.jpg",
        name : "Sara",
        fullName : "Sara Enriquez",
        rank : "../img/noRank.png",
        subject : "Matemáticas financieras",
        career : 'Finanzas y contabilidad',
        semester : 6,
        rating : "5/5",
        price : '$300',
        promedio : 9.8,
        comments : ['Me gustó, cómo me explicó lo que no entendía, es muy paciente', 'Tomen asesoría con él, entendí todo', 'Pensé que entendería este tema, muchas gracias', 'Excelente', 'Sabe mucho y explica muy bien.', 'Me ayudaste mucho ¡Gracias!', 'Entendí todo', 'Muy buena asesoría.', '¡Gracias! Me siento preparado para el examen.'],
        university : 'Anáhuac Mayab',
        description : 'Soy una estudiante que le encanta las matemáticas y enseñar a los demás. Además, soy paciente y si el tema se te complica mucho, haré todo lo posible hasta que lo entiendas.',
    }
];

let authors = ['Mateo', 'Santiago', 'Valentina', 'Maria Fernanda', 'Diego', 'Alejandro', 'Miguel Angel', 'Mia', 'Gisela', 'Alejandro (Tú)', 'Alejandro (Tú)', 'Alejandro (Tú)', 'Alejandro (Tú)', 'Alejandro (Tú)', 'Alejandro (Tú)'];

let messages = [];