let cards = [
    {
        image : "/img/profil1.jpg",
        name : "Lucas",
        fullName : "Lucas Martínez",
        rank : "/img/bronze-medal.png",
        subject : "Ingeniería",
        semester : 5,
        rating : "4/5",
        price : '250$',
        comments : ['Me gustó, cómo me explicó lo que no entendía, es muy paciente', 'Tomen asesoría con él, entendí todo', 'Pensé que entendería este tema, muchas gracias', 'Excelente', 'Sabe mucho y explica muy bien.', 'Me ayudaste mucho ¡Gracias!', 'Entendí todo', 'Muy buena asesoría.', '¡Gracias! Me siento preparado para el examen.'],
        university : 'Anahuac Mayab',
        description : 'Soy un estudiante que le encanta las matemáticas y ensenar a los demás. Además, soy paciente y si el tema se te complica mucho, haré todo lo posible hasta que lo entiendas.',
    },
    {
        image : "/img/profil5.jpg",
        name : "Tarik",
        fullName : "Tarik Rodriguez",
        rank : "/img/bronze-medal.png",
        subject : "Ingeniería",
        semester : 4,
        rating : "4/5",
        price : '250$',
        comments : ['Me gustó, cómo me explicó lo que no entendía, es muy paciente', 'Tomen asesoría con él, entendí todo', 'Pensé que entendería este tema, muchas gracias', 'Excelente', 'Sabe mucho y explica muy bien.', 'Me ayudaste mucho ¡Gracias!', 'Entendí todo', 'Muy buena asesoría.', '¡Gracias! Me siento preparado para el examen.'],
        university : 'Anahuac Mayab',
        description : 'Soy un estudiante que le encanta las matemáticas y ensenar a los demás. Además, soy paciente y si el tema se te complica mucho, haré todo lo posible hasta que lo entiendas.',
    },
    {
        image : "/img/profil2.jpg",
        name : "Maria",
        fullName : "Maria Méndez",
        rank : "/img/gold-medal.png",
        subject : "Administration",
        semester : 4,
        rating : "5/5",
        price : '300$',
        comments : ['Me gustó, cómo me explicó lo que no entendía, es muy paciente', 'Tomen asesoría con él, entendí todo', 'Pensé que entendería este tema, muchas gracias', 'Excelente', 'Sabe mucho y explica muy bien.', 'Me ayudaste mucho ¡Gracias!', 'Entendí todo', 'Muy buena asesoría.', '¡Gracias! Me siento preparado para el examen.'],
        university : 'Anahuac Mayab',
        description : 'Soy un estudiante que le encanta las matemáticas y ensenar a los demás. Además, soy paciente y si el tema se te complica mucho, haré todo lo posible hasta que lo entiendas.',
    },
    {
        image : "/img/profil7.jpg",
        name : "Elena",
        fullName : "Elena Sanz",
        rank : "/img/gold-medal.png",
        subject : "Matemáticas",
        semester : 5,
        rating : "4.5/5",
        price : '300$',
        comments : ['Me gustó, cómo me explicó lo que no entendía, es muy paciente', 'Tomen asesoría con él, entendí todo', 'Pensé que entendería este tema, muchas gracias', 'Excelente', 'Sabe mucho y explica muy bien.', 'Me ayudaste mucho ¡Gracias!', 'Entendí todo', 'Muy buena asesoría.', '¡Gracias! Me siento preparado para el examen.'],
        university : 'Anahuac Mayab',
        description : 'Soy un estudiante que le encanta las matemáticas y ensenar a los demás. Además, soy paciente y si el tema se te complica mucho, haré todo lo posible hasta que lo entiendas.',
    },
    {
        image : "/img/profil8.jpg",
        name : "Job",
        fullName : "Job López",
        rank : "/img/noRank.png",
        subject : "Ingeniería",
        semester : 2,
        rating : "4/5",
        price : '250$',
        comments : ['Me gustó, cómo me explicó lo que no entendía, es muy paciente', 'Tomen asesoría con él, entendí todo', 'Pensé que entendería este tema, muchas gracias', 'Excelente', 'Sabe mucho y explica muy bien.', 'Me ayudaste mucho ¡Gracias!', 'Entendí todo', 'Muy buena asesoría.', '¡Gracias! Me siento preparado para el examen.'],
        university : 'Anahuac Mayab',
        description : 'Soy un estudiante que le encanta las matemáticas y ensenar a los demás. Además, soy paciente y si el tema se te complica mucho, haré todo lo posible hasta que lo entiendas.',
    },
    {
        image : "/img/profil6.png",
        name : "Paola",
        fullName : "Paola Sánchez",
        rank : "/img/noRank.png",
        subject : "Matemáticas",
        semester : 2,
        rating : "4/5",
        price : '200$',
        comments : ['Me gustó, cómo me explicó lo que no entendía, es muy paciente', 'Tomen asesoría con él, entendí todo', 'Pensé que entendería este tema, muchas gracias', 'Excelente', 'Sabe mucho y explica muy bien.', 'Me ayudaste mucho ¡Gracias!', 'Entendí todo', 'Muy buena asesoría.', '¡Gracias! Me siento preparado para el examen.'],
        university : 'Anahuac Mayab',
        description : 'Soy un estudiante que le encanta las matemáticas y ensenar a los demás. Además, soy paciente y si el tema se te complica mucho, haré todo lo posible hasta que lo entiendas.',
    },
    {
        image : "/img/profil7.jpg",
        name : "Samuel",
        fullName : "Samuel Fernández",
        rank : "/img/gold-medal.png",
        subject : "Administration",
        semester : "6",
        rating : "4.5/5",
        price : '280$',
        comments : ['Me gustó, cómo me explicó lo que no entendía, es muy paciente', 'Tomen asesoría con él, entendí todo', 'Pensé que entendería este tema, muchas gracias', 'Excelente', 'Sabe mucho y explica muy bien.', 'Me ayudaste mucho ¡Gracias!', 'Entendí todo', 'Muy buena asesoría.', '¡Gracias! Me siento preparado para el examen.'],
        university : 'Anahuac Mayab',
        description : 'Soy un estudiante que le encanta las matemáticas y ensenar a los demás. Además, soy paciente y si el tema se te complica mucho, haré todo lo posible hasta que lo entiendas.',
    }
];

let authors = ['Mateo', 'Santiago', 'Valentina', 'Maria Fernanda', 'Diego', 'Alejandro', 'Miguel Angel', 'Mia', 'Gisela', 'Daniel'];

let messages = [];